# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d24ea2a0acc592412b7522dac36c766ff5d99b9722930eb2eaab18970df2d864dec0438e4d8ac625df5af8c0ed645ed0bdbf33724defc819aed2412ea548adf

test:
  secret_key_base: 6553eb28bc535540f166330220a66b6cbd4372f1df79d252c2a2cf855c3fe83a07b7039fb784dc637003250eb48ac451470529beeeee698669afc94f0d027255

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
